import type { ValueOf } from "../domain";

export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  NOT_FOUND: "NOT_FOUND",
  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  INVALID_WORKFLOW_TRANSITION: "INVALID_WORKFLOW_TRANSITION",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTEGRATION_ERROR: "INTEGRATION_ERROR",
  GO_EXECUTOR_ERROR: "GO_EXECUTOR_ERROR",
  AI_REVIEW_ERROR: "AI_REVIEW_ERROR",
  SYSTEM_ERROR: "SYSTEM_ERROR",
} as const;

export type ErrorCode = ValueOf<typeof ERROR_CODES>;
