// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

// Package clients holds the TOOL-007 generated transport-agnostic
// capability clients for IntentService and RegistryService: one interface
// per service, a native gRPC backend and a connect-go backend, both
// decoding a failure into the identical *envelope.Error (see
// DecodeGRPCError, DecodeConnectError). PROTO-006's parity suite exercises
// both backends against the shared internal/transport/transporttest fixture
// and requires them to agree on everything: domain result, typed error,
// evidence identifiers, deadline propagation, and the refusal of a
// caller-selected trusted-context header.
//
// Regenerate with `go run ./tools/gen/clients/cmd/generateclients`.
package clients
