// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

import (
	"context"

	"connectrpc.com/connect"
	registryv1 "github.com/monstercameron/human-capital-management-suite/gen/go/hcmnext/registry/v1"
	"google.golang.org/grpc"
)

// Procedure paths for hcmnext.registry.v1.RegistryService, identical to the gRPC method's
// FullMethod and to connect.Spec.Procedure.
const (
	ProcedureGetCapability         = "/hcmnext.registry.v1.RegistryService/GetCapability"
	ProcedureGetIntentDefinition   = "/hcmnext.registry.v1.RegistryService/GetIntentDefinition"
	ProcedureListCapabilities      = "/hcmnext.registry.v1.RegistryService/ListCapabilities"
	ProcedureListIntentDefinitions = "/hcmnext.registry.v1.RegistryService/ListIntentDefinitions"
)

// ProceduresRegistryService returns every procedure path RegistryClient
// publishes, in manifest order.
func ProceduresRegistryService() []string {
	return []string{
		ProcedureGetCapability,
		ProcedureGetIntentDefinition,
		ProcedureListCapabilities,
		ProcedureListIntentDefinitions,
	}
}

// RegistryClient is the transport-agnostic capability client for
// hcmnext.registry.v1.RegistryService. Both [NewRegistryClientGRPC] and [NewRegistryClientConnect]
// decode a failure into the identical *envelope.Error (DecodeGRPCError,
// DecodeConnectError), so calling code does not depend on which backend it
// was built with.
type RegistryClient interface {
	// GetCapability calls hcmnext.registry.v1.RegistryService.GetCapability.
	GetCapability(ctx context.Context, req *registryv1.GetCapabilityRequest, opts ...CallOption) (*registryv1.GetCapabilityResponse, error)
	// GetIntentDefinition calls hcmnext.registry.v1.RegistryService.GetIntentDefinition.
	GetIntentDefinition(ctx context.Context, req *registryv1.GetIntentDefinitionRequest, opts ...CallOption) (*registryv1.GetIntentDefinitionResponse, error)
	// ListCapabilities calls hcmnext.registry.v1.RegistryService.ListCapabilities.
	ListCapabilities(ctx context.Context, req *registryv1.ListCapabilitiesRequest, opts ...CallOption) (*registryv1.ListCapabilitiesResponse, error)
	// ListIntentDefinitions calls hcmnext.registry.v1.RegistryService.ListIntentDefinitions.
	ListIntentDefinitions(ctx context.Context, req *registryv1.ListIntentDefinitionsRequest, opts ...CallOption) (*registryv1.ListIntentDefinitionsResponse, error)
}

// registryGRPCClient is the native gRPC backend for RegistryClient.
type registryGRPCClient struct {
	client registryv1.RegistryServiceClient
}

// NewRegistryClientGRPC builds a RegistryClient that calls hcmnext.registry.v1.RegistryService
// over native gRPC on cc.
func NewRegistryClientGRPC(cc grpc.ClientConnInterface) RegistryClient {
	return &registryGRPCClient{client: registryv1.NewRegistryServiceClient(cc)}
}

// GetCapability calls hcmnext.registry.v1.RegistryService.GetCapability over native gRPC.
func (c *registryGRPCClient) GetCapability(ctx context.Context, req *registryv1.GetCapabilityRequest, opts ...CallOption) (*registryv1.GetCapabilityResponse, error) {
	res, err := c.client.GetCapability(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// GetIntentDefinition calls hcmnext.registry.v1.RegistryService.GetIntentDefinition over native gRPC.
func (c *registryGRPCClient) GetIntentDefinition(ctx context.Context, req *registryv1.GetIntentDefinitionRequest, opts ...CallOption) (*registryv1.GetIntentDefinitionResponse, error) {
	res, err := c.client.GetIntentDefinition(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListCapabilities calls hcmnext.registry.v1.RegistryService.ListCapabilities over native gRPC.
func (c *registryGRPCClient) ListCapabilities(ctx context.Context, req *registryv1.ListCapabilitiesRequest, opts ...CallOption) (*registryv1.ListCapabilitiesResponse, error) {
	res, err := c.client.ListCapabilities(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// ListIntentDefinitions calls hcmnext.registry.v1.RegistryService.ListIntentDefinitions over native gRPC.
func (c *registryGRPCClient) ListIntentDefinitions(ctx context.Context, req *registryv1.ListIntentDefinitionsRequest, opts ...CallOption) (*registryv1.ListIntentDefinitionsResponse, error) {
	res, err := c.client.ListIntentDefinitions(applyGRPCOptions(ctx, opts), req)
	if err != nil {
		return nil, DecodeGRPCError(err)
	}
	return res, nil
}

// registryConnectClient is the connect-go backend for RegistryClient.
type registryConnectClient struct {
	getCapability         *connect.Client[registryv1.GetCapabilityRequest, registryv1.GetCapabilityResponse]
	getIntentDefinition   *connect.Client[registryv1.GetIntentDefinitionRequest, registryv1.GetIntentDefinitionResponse]
	listCapabilities      *connect.Client[registryv1.ListCapabilitiesRequest, registryv1.ListCapabilitiesResponse]
	listIntentDefinitions *connect.Client[registryv1.ListIntentDefinitionsRequest, registryv1.ListIntentDefinitionsResponse]
}

// NewRegistryClientConnect builds a RegistryClient that calls the
// hcmnext.registry.v1.RegistryService procedures published at baseURL over connect-go.
func NewRegistryClientConnect(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RegistryClient {
	return &registryConnectClient{
		getCapability:         connect.NewClient[registryv1.GetCapabilityRequest, registryv1.GetCapabilityResponse](httpClient, baseURL+ProcedureGetCapability, opts...),
		getIntentDefinition:   connect.NewClient[registryv1.GetIntentDefinitionRequest, registryv1.GetIntentDefinitionResponse](httpClient, baseURL+ProcedureGetIntentDefinition, opts...),
		listCapabilities:      connect.NewClient[registryv1.ListCapabilitiesRequest, registryv1.ListCapabilitiesResponse](httpClient, baseURL+ProcedureListCapabilities, opts...),
		listIntentDefinitions: connect.NewClient[registryv1.ListIntentDefinitionsRequest, registryv1.ListIntentDefinitionsResponse](httpClient, baseURL+ProcedureListIntentDefinitions, opts...),
	}
}

// GetCapability calls hcmnext.registry.v1.RegistryService.GetCapability over connect-go.
func (c *registryConnectClient) GetCapability(ctx context.Context, req *registryv1.GetCapabilityRequest, opts ...CallOption) (*registryv1.GetCapabilityResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getCapability.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// GetIntentDefinition calls hcmnext.registry.v1.RegistryService.GetIntentDefinition over connect-go.
func (c *registryConnectClient) GetIntentDefinition(ctx context.Context, req *registryv1.GetIntentDefinitionRequest, opts ...CallOption) (*registryv1.GetIntentDefinitionResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.getIntentDefinition.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListCapabilities calls hcmnext.registry.v1.RegistryService.ListCapabilities over connect-go.
func (c *registryConnectClient) ListCapabilities(ctx context.Context, req *registryv1.ListCapabilitiesRequest, opts ...CallOption) (*registryv1.ListCapabilitiesResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listCapabilities.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}

// ListIntentDefinitions calls hcmnext.registry.v1.RegistryService.ListIntentDefinitions over connect-go.
func (c *registryConnectClient) ListIntentDefinitions(ctx context.Context, req *registryv1.ListIntentDefinitionsRequest, opts ...CallOption) (*registryv1.ListIntentDefinitionsResponse, error) {
	connectReq := connect.NewRequest(req)
	applyConnectOptions(connectReq, opts)
	res, err := c.listIntentDefinitions.CallUnary(ctx, connectReq)
	if err != nil {
		return nil, DecodeConnectError(err)
	}
	return res.Msg, nil
}
