// Code generated by tools/gen/clients from definitions/api/endpoint-manifest.json. DO NOT EDIT.

package clients

import (
	"context"
	"errors"

	"connectrpc.com/connect"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"

	commonv1 "github.com/monstercameron/hcm-next/gen/go/hcmnext/common/v1"
	"github.com/monstercameron/hcm-next/internal/transport"
	"github.com/monstercameron/hcm-next/internal/transport/envelope"
)

// CallOptions carries the per-call metadata a [CallOption] sets.
type CallOptions struct {
	Headers map[string]string
}

// CallOption configures one outbound call. Both backends project the same
// key onto their own header/metadata shape identically: the same key
// becomes the same gRPC metadata key and the same HTTP header, because
// gRPC-Go and connect-go both canonicalize keys to lower case.
type CallOption func(*CallOptions)

// WithHeader sets one outbound header/metadata key. A repeated key keeps
// its last value.
func WithHeader(key, value string) CallOption {
	return func(o *CallOptions) {
		if o.Headers == nil {
			o.Headers = make(map[string]string, 1)
		}
		o.Headers[key] = value
	}
}

// WithAuthorization sets the request's credential, e.g. "Bearer <token>".
func WithAuthorization(credential string) CallOption {
	return WithHeader(transport.AuthorizationMetadataKey, credential)
}

// WithRequestID sets the caller's own correlation identifier.
func WithRequestID(id string) CallOption {
	return WithHeader(transport.RequestIDMetadataKey, id)
}

// newCallOptions applies opts in order.
func newCallOptions(opts []CallOption) *CallOptions {
	o := &CallOptions{}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// applyGRPCOptions projects opts onto ctx as outgoing gRPC metadata.
func applyGRPCOptions(ctx context.Context, opts []CallOption) context.Context {
	o := newCallOptions(opts)
	if len(o.Headers) == 0 {
		return ctx
	}
	pairs := make([]string, 0, len(o.Headers)*2)
	for k, v := range o.Headers {
		pairs = append(pairs, k, v)
	}
	return metadata.AppendToOutgoingContext(ctx, pairs...)
}

// applyConnectOptions projects opts onto req's outbound HTTP headers.
func applyConnectOptions[T any](req *connect.Request[T], opts []CallOption) {
	o := newCallOptions(opts)
	for k, v := range o.Headers {
		req.Header().Set(k, v)
	}
}

// DecodeGRPCError extracts the owned *envelope.Error from a native gRPC
// client failure. err is returned unchanged when it carries no gRPC status.
func DecodeGRPCError(err error) error {
	if err == nil {
		return nil
	}
	if owned, ok := envelope.FromGRPC(err); ok {
		return owned
	}
	return err
}

// DecodeConnectError extracts the owned *envelope.Error from a connect-go
// client failure, projecting the same hcmnext.common.v1.ErrorDetail
// [envelope.FromGRPC] does, so a caller sees an identical *envelope.Error
// regardless of which backend produced it. err is returned unchanged when
// it is not a *connect.Error.
func DecodeConnectError(err error) error {
	if err == nil {
		return nil
	}
	var connectErr *connect.Error
	if !errors.As(err, &connectErr) {
		return err
	}
	var detail *commonv1.ErrorDetail
	for _, d := range connectErr.Details() {
		value, valueErr := d.Value()
		if valueErr != nil {
			continue
		}
		if ed, ok := value.(*commonv1.ErrorDetail); ok {
			detail = ed
			break
		}
	}
	return envelope.FromDetail(envelope.CodeFromGRPC(codes.Code(connectErr.Code())), connectErr.Message(), detail)
}
