import type { ValueOf } from "../domain";

export const LEDGER_EVENT_TYPES = {
  WORKFLOW_INTENT_STARTED: "WorkflowIntentStarted",
  WORKFLOW_TRANSITION_SUBMITTED: "WorkflowTransitionSubmitted",
  WORKFLOW_STATE_CHANGED: "WorkflowStateChanged",
  CHANGE_REQUEST_CREATED: "ChangeRequestCreated",
  PROPOSED_CHANGE_CREATED: "ProposedChangeCreated",
  NAME_CHANGE_PREFLIGHTED: "NameChangePreflighted",
  EMERGENCY_CONTACT_PREFLIGHTED: "EmergencyContactPreflighted",
  CONTACT_INFO_PREFLIGHTED: "ContactInfoPreflighted",
  COMPENSATION_PREFLIGHTED: "CompensationPreflighted",
  ORG_TRANSFER_PREFLIGHTED: "OrgTransferPreflighted",
  ORG_TRANSFER_SUBMITTED: "OrgTransferSubmitted",
  EVIDENCE_REQUESTED: "EvidenceRequested",
  DOCUMENT_CREATED: "DocumentCreated",
  EVIDENCE_PROVIDED: "EvidenceProvided",
  APPROVAL_TASK_CREATED: "ApprovalTaskCreated",
  SOURCE_MANAGER_APPROVAL_CREATED: "SourceManagerApprovalCreated",
  DESTINATION_MANAGER_APPROVAL_CREATED: "DestinationManagerApprovalCreated",
  FINANCE_APPROVAL_CREATED: "FinanceApprovalCreated",
  COMPENSATION_APPROVAL_CREATED: "CompensationApprovalCreated",
  CLINICAL_PLACEMENT_APPROVAL_CREATED: "ClinicalPlacementApprovalCreated",
  CHANGE_REQUEST_SUBMITTED: "ChangeRequestSubmitted",
  APPROVAL_GRANTED: "ApprovalGranted",
  APPROVAL_REJECTED: "ApprovalRejected",
  MORE_INFORMATION_REQUESTED: "MoreInformationRequested",
  CHANGE_REQUEST_APPROVED: "ChangeRequestApproved",
  CHANGE_REQUEST_REJECTED: "ChangeRequestRejected",
  TRANSACTION_PLAN_CREATED: "TransactionPlanCreated",
  TRANSACTION_EXECUTION_STARTED: "TransactionExecutionStarted",
  PERSON_LEGAL_NAME_CHANGED: "PersonLegalNameChanged",
  EMPLOYEE_EMERGENCY_CONTACT_UPDATED: "EmployeeEmergencyContactUpdated",
  EMPLOYEE_CONTACT_INFO_UPDATED: "EmployeeContactInfoUpdated",
  EMPLOYEE_COMPENSATION_UPDATED: "EmployeeCompensationUpdated",
  WORKER_ASSIGNMENT_SUPERSEDED: "WorkerAssignmentSuperseded",
  WORKER_ASSIGNMENT_CREATED: "WorkerAssignmentCreated",
  ROLE_BINDINGS_RECALCULATED: "RoleBindingsRecalculated",
  EMPLOYEE_PROJECTION_UPDATED: "EmployeeProjectionUpdated",
  EMPLOYEE_ORG_PROJECTION_UPDATED: "EmployeeOrgProjectionUpdated",
  EXTERNAL_WRITE_REQUESTED: "ExternalWriteRequested",
  EXTERNAL_WRITE_SUCCEEDED: "ExternalWriteSucceeded",
  EXTERNAL_WRITE_FAILED: "ExternalWriteFailed",
  TRANSACTION_EXECUTION_COMPLETED: "TransactionExecutionCompleted",
  ORG_TRANSFER_EXECUTED: "OrgTransferExecuted",
  WORKFLOW_COMPLETED: "WorkflowCompleted",
  WORKFLOW_CANCELED: "WorkflowCanceled",
  WORKFLOW_FAILED: "WorkflowFailed",
} as const;

export type LedgerEventType = ValueOf<typeof LEDGER_EVENT_TYPES>;
