// Code generated by the workflowdesign command; DO NOT EDIT.

package registry

// RecordCount is the number of design records in this registry.
const RecordCount = 14

// Intents lists every registered intent in canonical order.
var Intents = []string{
	"ApproveProposal",
	"ChangeBasePay",
	"ChangeManager",
	"CreateRepairPlan",
	"DetectDrift",
	"EvaluatePayBandPosition",
	"ExplainTransaction",
	"ExplainWorkerState",
	"PromoteWorker",
	"RejectProposal",
	"ReleaseCompensationBudget",
	"ReserveCompensationBudget",
	"SimulateCompensation",
	"SimulateRepair",
}
