package transformationvectors

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// Generate writes a deterministic Go test source file to outDir. Callers
// should pass a temporary directory; the generator never writes repository
// fixtures or modifies production sources.
func Generate(outDir, packageName string, vectors []Vector) (string, error) {
	if outDir == "" || packageName == "" {
		return "", fmt.Errorf("output directory and package are required")
	}
	if len(vectors) == 0 {
		return "", fmt.Errorf("at least one vector is required")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by transformationvectors; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package %s\n\nimport (\n    \"testing\"\n    tv \"github.com/monstercameron/hcm-next/tools/conformance/transformationvectors\"\n)\n\n", packageName)
	b.WriteString("func TestGeneratedXFORM006(t *testing.T) {\n")
	for _, v := range vectors {
		fmt.Fprintf(&b, "    t.Run(%q, func(t *testing.T) { tv.RunGeneratedForTest(t, %q) })\n", v.Name, v.Name)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return "", fmt.Errorf("format generated source: %w", err)
	}
	path := filepath.Join(outDir, "xform006_generated_test.go")
	if err := os.WriteFile(path, src, 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// RunGeneratedForTest is the small stable hook used by generated tests.
func RunGeneratedForTest(t testLogger, name string) {
	for _, v := range DefaultVectors() {
		if v.Name == name {
			runVector(t, v)
			return
		}
	}
	t.Fatalf("unknown generated vector %q", name)
}
