package balance

import (
	"errors"
	"fmt"
	"strings"

	"github.com/monstercameron/human-capital-management-suite/internal/engines/canonicalbytes"
	"github.com/monstercameron/human-capital-management-suite/internal/kernel/values"
)

// Lifecycle entries are reserved for entries generated by ApplyLifecycle.
const (
	ExpiryEntryType    = "BALANCE_EXPIRY"
	CarryoverEntryType = "BALANCE_CARRYOVER"
	RolloverEntryType  = "BALANCE_ROLLOVER"
)

// LifecycleOperation identifies the reason for one generated entry.
type LifecycleOperation string

const (
	LifecycleExpiry    LifecycleOperation = "EXPIRY"
	LifecycleCarryover LifecycleOperation = "CARRYOVER"
	LifecycleRollover  LifecycleOperation = "ROLLOVER"
)

// PeriodDefinition is an explicit half-open UTC period [Start, End). Instants
// make rollover independent of DST and host timezone data.
type PeriodDefinition struct {
	ID      string
	Version string
	Kind    PeriodKind
	Start   values.Instant
	End     values.Instant
}

// ExpiryPolicy declares whether positive source-period value expires.
type ExpiryPolicy struct {
	ID      string
	Version string
	Enabled bool
}

// CarryoverPolicy declares whether positive value transfers. An unset Cap is
// unlimited; a set Cap limits the transferred amount.
type CarryoverPolicy struct {
	ID      string
	Version string
	Enabled bool
	Cap     values.Decimal
}

// RolloverPolicy declares the period-transfer policy version. When enabled,
// transfers are typed ROLLOVER; otherwise enabled carryover is typed CARRYOVER.
type RolloverPolicy struct {
	ID      string
	Version string
	Enabled bool
}

// BalanceLifecyclePolicy is the immutable policy input to ApplyLifecycle.
type BalanceLifecyclePolicy struct {
	Expiry    ExpiryPolicy
	Carryover CarryoverPolicy
	Rollover  RolloverPolicy
}

// LifecycleRequest declares the source/target periods and ledger identity.
type LifecycleRequest struct {
	AccountID string
	Period    PeriodDefinition
	Next      PeriodDefinition
	Template  BalanceEntry
	Opening   values.Decimal
	Scale     int32
	Rounding  values.RoundingMode
	Policy    BalanceLifecyclePolicy
	Ledger    []BalanceEntry
}

// ApplyLifecycleRequest is a compatibility name for LifecycleRequest.
type ApplyLifecycleRequest = LifecycleRequest

// LifecycleEntry is an effective-dated entry with source/target provenance.
type LifecycleEntry struct {
	Entry         BalanceEntry
	Operation     LifecycleOperation
	Reason        string
	PolicyID      string
	PolicyVersion string
	SourcePeriod  PeriodDefinition
	TargetPeriod  PeriodDefinition
	SourceEntries []string
}

// LifecycleExplanation states what expired or transferred and why.
type LifecycleExplanation struct {
	Operation     LifecycleOperation
	Amount        values.Decimal
	Reason        string
	PolicyID      string
	PolicyVersion string
	EffectiveAt   values.Instant
	SourceEntries []string
}

// LifecycleResult is the complete pure period transition derivation.
type LifecycleResult struct {
	AccountID     string
	SourcePeriod  PeriodDefinition
	TargetPeriod  PeriodDefinition
	SourceBalance values.Decimal
	Expired       values.Decimal
	Carried       values.Decimal
	Entries       []LifecycleEntry
	Explanation   []LifecycleExplanation
	Digest        string
}

var (
	ErrLifecycleInvalid = errors.New("balance: invalid lifecycle application")
	ErrPeriodInvalid    = errors.New("balance: invalid period definition")
)

// ApplyLifecycle derives expiry and period-transfer entries from a declared
// half-open period. It never edits prior entries and ignores lifecycle entries
// already present, so repeating the derivation cannot duplicate value.
func ApplyLifecycle(req LifecycleRequest) (LifecycleResult, error) {
	if err := validateLifecycleRequest(req); err != nil {
		return LifecycleResult{}, err
	}
	zero, err := values.NewDecimal("0", req.Scale, req.Rounding)
	if err != nil {
		return LifecycleResult{}, fmt.Errorf("%w: zero: %v", ErrLifecycleInvalid, err)
	}
	sourceBalance := req.Opening
	var sourceKeys []string
	for _, source := range req.Ledger {
		if source.AccountID != req.AccountID || isLifecycleEntryType(source.EntryType) {
			continue
		}
		if !source.EffectiveAt.IsSet() {
			return LifecycleResult{}, fmt.Errorf("%w: entry %q has no effective_at", ErrLifecycleInvalid, source.IdempotencyKey)
		}
		if source.EffectiveAt.Before(req.Period.Start) || !source.EffectiveAt.Before(req.Period.End) {
			continue
		}
		amount, e := source.Amount.Quantize(req.Scale, req.Rounding)
		if e != nil || amount.Sign() <= 0 {
			if e == nil {
				e = errors.New("amount must be positive")
			}
			return LifecycleResult{}, fmt.Errorf("%w: entry %q amount: %v", ErrLifecycleInvalid, source.IdempotencyKey, e)
		}
		delta, e := signedContribution(source.Kind, amount)
		if e != nil {
			return LifecycleResult{}, fmt.Errorf("%w: entry %q: %v", ErrLifecycleInvalid, source.IdempotencyKey, e)
		}
		sourceBalance, e = sourceBalance.Add(delta)
		if e != nil {
			return LifecycleResult{}, fmt.Errorf("%w: source balance: %v", ErrLifecycleInvalid, e)
		}
		sourceKeys = append(sourceKeys, source.IdempotencyKey)
	}
	result := LifecycleResult{AccountID: req.AccountID, SourcePeriod: req.Period, TargetPeriod: req.Next, SourceBalance: sourceBalance, Expired: zero, Carried: zero}
	if sourceBalance.Sign() > 0 {
		carried, expired, e := lifecycleAmounts(sourceBalance, req)
		if e != nil {
			return LifecycleResult{}, e
		}
		result.Carried, result.Expired = carried, expired
		sources := append([]string(nil), sourceKeys...)
		if expired.Sign() > 0 {
			policy := req.Policy.Expiry
			entry := lifecycleBalanceEntry(req.Template, expired, Debit, ExpiryEntryType, req.Period.End, "BAL-005:expiry:"+req.Period.ID)
			result.addLifecycleEntry(LifecycleEntry{Entry: entry, Operation: LifecycleExpiry, Reason: "UNUSED_VALUE_EXPIRED_AT_PERIOD_END", PolicyID: policy.ID, PolicyVersion: policy.Version, SourcePeriod: req.Period, TargetPeriod: req.Next, SourceEntries: sources})
		}
		if carried.Sign() > 0 {
			op, entryType := LifecycleCarryover, CarryoverEntryType
			policyID, policyVersion, reason := req.Policy.Carryover.ID, req.Policy.Carryover.Version, "VALUE_CARRIED_TO_NEXT_PERIOD"
			if req.Policy.Rollover.Enabled {
				op, entryType = LifecycleRollover, RolloverEntryType
				policyID, policyVersion, reason = req.Policy.Rollover.ID, req.Policy.Rollover.Version, "VALUE_ROLLED_TO_NEXT_PERIOD"
			}
			debitKey := fmt.Sprintf("BAL-005:%s:debit:%s", strings.ToLower(string(op)), req.Period.ID)
			creditKey := fmt.Sprintf("BAL-005:%s:credit:%s", strings.ToLower(string(op)), req.Next.ID)
			debit := lifecycleBalanceEntry(req.Template, carried, Debit, entryType, req.Period.End, debitKey)
			credit := lifecycleBalanceEntry(req.Template, carried, Credit, entryType, req.Next.Start, creditKey)
			result.addLifecycleEntry(LifecycleEntry{Entry: debit, Operation: op, Reason: reason + " (source transfer)", PolicyID: policyID, PolicyVersion: policyVersion, SourcePeriod: req.Period, TargetPeriod: req.Next, SourceEntries: sources})
			result.addLifecycleEntry(LifecycleEntry{Entry: credit, Operation: op, Reason: reason, PolicyID: policyID, PolicyVersion: policyVersion, SourcePeriod: req.Period, TargetPeriod: req.Next, SourceEntries: sources})
		}
	}
	for _, entry := range result.Entries {
		result.Explanation = append(result.Explanation, LifecycleExplanation{Operation: entry.Operation, Amount: entry.Entry.Amount, Reason: entry.Reason, PolicyID: entry.PolicyID, PolicyVersion: entry.PolicyVersion, EffectiveAt: entry.Entry.EffectiveAt, SourceEntries: append([]string(nil), entry.SourceEntries...)})
	}
	result.Digest, err = lifecycleDigest(result)
	if err != nil {
		return LifecycleResult{}, fmt.Errorf("%w: digest: %v", ErrLifecycleInvalid, err)
	}
	return result, nil
}

// ApplyExpiryCarryoverRollover is a descriptive spelling for ApplyLifecycle.
func ApplyExpiryCarryoverRollover(req LifecycleRequest) (LifecycleResult, error) {
	return ApplyLifecycle(req)
}

func validateLifecycleRequest(req LifecycleRequest) error {
	if strings.TrimSpace(req.AccountID) == "" {
		return fmt.Errorf("%w: account_id is required", ErrLifecycleInvalid)
	}
	if err := req.Opening.Validate(); err != nil || req.Opening.Scale() != req.Scale {
		return fmt.Errorf("%w: opening must be valid at scale %d: %v", ErrLifecycleInvalid, req.Scale, err)
	}
	if !req.Rounding.Valid() {
		return fmt.Errorf("%w: rounding must be declared", ErrLifecycleInvalid)
	}
	if err := req.Period.Validate(); err != nil {
		return err
	}
	if err := req.Next.Validate(); err != nil {
		return err
	}
	if req.Period.Kind != req.Next.Kind || req.Period.End.Compare(req.Next.Start) != 0 {
		return fmt.Errorf("%w: source and target periods must be contiguous and have the same kind", ErrPeriodInvalid)
	}
	if req.Template.AccountID != req.AccountID || strings.TrimSpace(req.Template.DefinitionID) == "" || strings.TrimSpace(req.Template.DefinitionVersion) == "" || strings.TrimSpace(req.Template.Unit) == "" || strings.TrimSpace(req.Template.Subject) == "" {
		return fmt.Errorf("%w: template identity is incomplete", ErrLifecycleInvalid)
	}
	if req.Template.Period != string(req.Period.Kind) {
		return fmt.Errorf("%w: template period does not match source period kind", ErrLifecycleInvalid)
	}
	if req.Policy.Expiry.Enabled && (strings.TrimSpace(req.Policy.Expiry.ID) == "" || strings.TrimSpace(req.Policy.Expiry.Version) == "") {
		return fmt.Errorf("%w: expiry policy id and version are required", ErrLifecycleInvalid)
	}
	if req.Policy.Carryover.Enabled && (strings.TrimSpace(req.Policy.Carryover.ID) == "" || strings.TrimSpace(req.Policy.Carryover.Version) == "") {
		return fmt.Errorf("%w: carryover policy id and version are required", ErrLifecycleInvalid)
	}
	if req.Policy.Rollover.Enabled && (strings.TrimSpace(req.Policy.Rollover.ID) == "" || strings.TrimSpace(req.Policy.Rollover.Version) == "") {
		return fmt.Errorf("%w: rollover policy id and version are required", ErrLifecycleInvalid)
	}
	if cap := req.Policy.Carryover.Cap; cap.Validate() == nil && (cap.Sign() < 0 || cap.Scale() != req.Scale) {
		return fmt.Errorf("%w: carryover cap must be non-negative at scale %d", ErrLifecycleInvalid, req.Scale)
	}
	return nil
}

func (p PeriodDefinition) Validate() error {
	if strings.TrimSpace(p.ID) == "" || strings.TrimSpace(p.Version) == "" {
		return fmt.Errorf("%w: id and version are required", ErrPeriodInvalid)
	}
	switch p.Kind {
	case PeriodPayPeriod, PeriodCalendarYear, PeriodFiscalYear, PeriodLifetime:
	default:
		return fmt.Errorf("%w: kind must be specified", ErrPeriodInvalid)
	}
	if !p.Start.IsSet() || !p.End.IsSet() || p.Start.Compare(p.End) >= 0 {
		return fmt.Errorf("%w: start and end must be set and start before end", ErrPeriodInvalid)
	}
	return nil
}

func lifecycleAmounts(source values.Decimal, req LifecycleRequest) (values.Decimal, values.Decimal, error) {
	zero := values.MustDecimal("0", req.Scale, req.Rounding)
	if !req.Policy.Carryover.Enabled && !req.Policy.Rollover.Enabled {
		if req.Policy.Expiry.Enabled {
			return zero, source, nil
		}
		return zero, zero, nil
	}
	carried := source
	if cap := req.Policy.Carryover.Cap; cap.Validate() == nil && carried.Cmp(cap) > 0 {
		carried = cap
	}
	expired := zero
	if req.Policy.Expiry.Enabled {
		var err error
		expired, err = source.Sub(carried)
		if err != nil {
			return values.Decimal{}, values.Decimal{}, fmt.Errorf("%w: expiry amount: %v", ErrLifecycleInvalid, err)
		}
	}
	return carried, expired, nil
}

func lifecycleBalanceEntry(template BalanceEntry, amount values.Decimal, kind EntryKind, entryType string, effectiveAt values.Instant, key string) BalanceEntry {
	entry := template.copy()
	entry.Kind, entry.Amount, entry.EntryType = kind, amount, entryType
	entry.EffectiveAt = effectiveAt
	entry.RecordedAt, entry.AuthorizedAt = values.Instant{}, values.Instant{}
	entry.SourceTransactionID, entry.IdempotencyKey = key, key
	return entry
}

func (r *LifecycleResult) addLifecycleEntry(entry LifecycleEntry) {
	r.Entries = append(r.Entries, entry)
}

func isLifecycleEntryType(entryType string) bool {
	return entryType == ExpiryEntryType || entryType == CarryoverEntryType || entryType == RolloverEntryType
}

func lifecycleDigest(result LifecycleResult) (string, error) {
	w := canonicalbytes.New("hcmnext.domains.balance.LifecycleResult", 1).String("account_id", result.AccountID).String("source_period.id", result.SourcePeriod.ID).String("source_period.version", result.SourcePeriod.Version).String("source_period.kind", string(result.SourcePeriod.Kind)).Value("source_period.start", result.SourcePeriod.Start).Value("source_period.end", result.SourcePeriod.End).String("target_period.id", result.TargetPeriod.ID).String("target_period.version", result.TargetPeriod.Version).String("target_period.kind", string(result.TargetPeriod.Kind)).Value("target_period.start", result.TargetPeriod.Start).Value("target_period.end", result.TargetPeriod.End).Value("source_balance", result.SourceBalance).Value("expired", result.Expired).Value("carried", result.Carried).Count("entries", len(result.Entries))
	for _, entry := range result.Entries {
		w = w.String("entry.digest", entry.Entry.Digest()).String("entry.operation", string(entry.Operation)).String("entry.reason", entry.Reason).String("entry.policy_id", entry.PolicyID).String("entry.policy_version", entry.PolicyVersion).Value("entry.effective_at", entry.Entry.EffectiveAt).Count("entry.sources", len(entry.SourceEntries))
		for _, source := range entry.SourceEntries {
			w = w.String("entry.source", source)
		}
	}
	return w.Digest()
}
