package balance

import (
	"errors"
	"fmt"
	"strings"

	"github.com/monstercameron/hcm-next/internal/engines/canonicalbytes"
	"github.com/monstercameron/hcm-next/internal/kernel/values"
)

// RuleApplicationEntryType is reserved for entries generated by ApplyRules.
const RuleApplicationEntryType = "BALANCE_POLICY_ADJUSTMENT"

// BalanceRuleKind identifies one ordered operation in a balance policy.
type BalanceRuleKind string

const (
	BalanceRuleFloor     BalanceRuleKind = "FLOOR"
	BalanceRuleCap       BalanceRuleKind = "CAP"
	BalanceRuleThreshold BalanceRuleKind = "THRESHOLD"
)

// BalanceRule is a single declared, versioned operation. Rules are evaluated
// in the order supplied to ApplyRules; order is part of the policy contract.
// AppliesTo may be empty to apply to every entry kind, or select DEBIT/CREDIT.
type BalanceRule struct {
	ID        string
	Version   string
	Kind      BalanceRuleKind
	AppliesTo EntryKind
	Limit     values.Decimal
}

// RuleApplicationRequest declares the arithmetic contract for ApplyRules.
type RuleApplicationRequest struct {
	AccountID string
	Opening   values.Decimal
	Scale     int32
	Rounding  values.RoundingMode
	Rules     []BalanceRule
}

// RuleApplication is a compatibility name for RuleApplicationRequest.
type RuleApplication = RuleApplicationRequest

// RuleAdjustment is a typed, explainable entry generated by a floor or cap.
type RuleAdjustment struct {
	Entry       BalanceEntry
	RuleID      string
	RuleVersion string
	RuleKind    BalanceRuleKind
	Reason      string
	SourceEntry string
}

// RuleDecision records one ordered rule evaluation for one source entry.
type RuleDecision struct {
	SourceEntry       string
	RuleID            string
	RuleVersion       string
	RuleKind          BalanceRuleKind
	Reason            string
	Accepted          values.Decimal
	Rejected          values.Decimal
	Overflow          values.Decimal
	ThresholdBreached bool
}

// RuleEvent is a typed event emitted in the pure result when a threshold is met.
type RuleEvent struct {
	Type        string
	RuleID      string
	RuleVersion string
	SourceEntry string
	Reason      string
}

// RuleApplicationResult is the complete deterministic derivation. Original
// entries remain unchanged; adjustments are explicit and never silent clamps.
type RuleApplicationResult struct {
	AccountID   string
	Opening     values.Decimal
	Ending      values.Decimal
	Accepted    values.Decimal
	Rejected    values.Decimal
	Overflow    values.Decimal
	Entries     []BalanceEntry
	Adjustments []RuleAdjustment
	Decisions   []RuleDecision
	Events      []RuleEvent
	Digest      string
}

var (
	ErrRuleApplicationInvalid = errors.New("balance: invalid rule application")
	ErrRuleInvalid            = errors.New("balance: invalid balance rule")
)

// ApplyRules evaluates entries in append order and rules in declaration order.
// A threshold accepts at most its Limit from one source movement; the
// remainder is rejected. Floors and caps adjust the running balance after each
// accepted movement and emit typed entries. The function is pure and safe to
// repeat over the same ledger.
func ApplyRules(req RuleApplicationRequest, ledger []BalanceEntry) (RuleApplicationResult, error) {
	if err := validateRuleApplication(req); err != nil {
		return RuleApplicationResult{}, err
	}
	zero, err := values.NewDecimal("0", req.Scale, req.Rounding)
	if err != nil {
		return RuleApplicationResult{}, fmt.Errorf("%w: zero: %v", ErrRuleApplicationInvalid, err)
	}
	running := req.Opening
	result := RuleApplicationResult{AccountID: req.AccountID, Opening: req.Opening, Accepted: zero, Rejected: zero, Overflow: zero}
	adjustmentNumber := 0
	for _, source := range ledger {
		if source.AccountID != req.AccountID || source.EntryType == RuleApplicationEntryType {
			continue
		}
		amount, err := source.Amount.Quantize(req.Scale, req.Rounding)
		if err != nil || amount.Sign() <= 0 {
			if err == nil {
				err = errors.New("amount must be positive")
			}
			return RuleApplicationResult{}, fmt.Errorf("%w: entry %q amount: %v", ErrRuleApplicationInvalid, source.IdempotencyKey, err)
		}
		if source.Kind != Debit && source.Kind != Credit {
			return RuleApplicationResult{}, fmt.Errorf("%w: entry %q kind %q", ErrRuleApplicationInvalid, source.IdempotencyKey, source.Kind)
		}
		accepted := amount
		delta, err := signedContribution(source.Kind, accepted)
		if err != nil {
			return RuleApplicationResult{}, fmt.Errorf("%w: %v", ErrRuleApplicationInvalid, err)
		}
		candidate, err := running.Add(delta)
		if err != nil {
			return RuleApplicationResult{}, fmt.Errorf("%w: entry %q: %v", ErrRuleApplicationInvalid, source.IdempotencyKey, err)
		}
		decisions := make([]RuleDecision, 0, len(req.Rules))
		for _, rule := range req.Rules {
			if rule.AppliesTo != "" && rule.AppliesTo != source.Kind {
				continue
			}
			decision := RuleDecision{SourceEntry: source.IdempotencyKey, RuleID: rule.ID, RuleVersion: rule.Version, RuleKind: rule.Kind, Accepted: accepted, Rejected: zero, Overflow: zero}
			switch rule.Kind {
			case BalanceRuleThreshold:
				if accepted.Cmp(rule.Limit) > 0 {
					previous := accepted
					accepted, err = rule.Limit.Quantize(req.Scale, req.Rounding)
					if err != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: threshold %q: %v", ErrRuleApplicationInvalid, rule.ID, err)
					}
					decision.Rejected, err = previous.Sub(accepted)
					if err != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: threshold rejection: %v", ErrRuleApplicationInvalid, err)
					}
					rejectedDelta, _ := previous.Sub(accepted)
					rejectedContribution, _ := signedContribution(source.Kind, rejectedDelta)
					candidate, err = candidate.Sub(rejectedContribution)
					if err != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: threshold candidate: %v", ErrRuleApplicationInvalid, err)
					}
					decision.ThresholdBreached = true
					decision.Reason = "THRESHOLD_EXCEEDED_REJECTED"
					result.Events = append(result.Events, RuleEvent{Type: "THRESHOLD_BREACHED", RuleID: rule.ID, RuleVersion: rule.Version, SourceEntry: source.IdempotencyKey, Reason: decision.Reason})
				} else if accepted.Equal(rule.Limit) {
					decision.ThresholdBreached = true
					decision.Reason = "THRESHOLD_MET"
					result.Events = append(result.Events, RuleEvent{Type: "THRESHOLD_MET", RuleID: rule.ID, RuleVersion: rule.Version, SourceEntry: source.IdempotencyKey, Reason: decision.Reason})
				} else {
					decision.Reason = "THRESHOLD_NOT_MET"
				}
			case BalanceRuleFloor, BalanceRuleCap:
				if rule.Kind == BalanceRuleFloor && candidate.Cmp(rule.Limit) < 0 {
					adjustmentAmount, e := rule.Limit.Sub(candidate)
					if e != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: floor %q: %v", ErrRuleApplicationInvalid, rule.ID, e)
					}
					candidate, e = candidate.Add(adjustmentAmount)
					if e != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: floor adjustment: %v", ErrRuleApplicationInvalid, e)
					}
					adjustmentNumber++
					result.Adjustments = append(result.Adjustments, makeRuleAdjustment(source, adjustmentAmount, Credit, rule, adjustmentNumber, "FLOOR_APPLIED"))
					decision.Reason = "FLOOR_APPLIED"
				} else if rule.Kind == BalanceRuleCap && candidate.Cmp(rule.Limit) > 0 {
					overflow, e := candidate.Sub(rule.Limit)
					if e != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: cap %q: %v", ErrRuleApplicationInvalid, rule.ID, e)
					}
					candidate, e = candidate.Sub(overflow)
					if e != nil {
						return RuleApplicationResult{}, fmt.Errorf("%w: cap adjustment: %v", ErrRuleApplicationInvalid, e)
					}
					adjustmentNumber++
					result.Adjustments = append(result.Adjustments, makeRuleAdjustment(source, overflow, Debit, rule, adjustmentNumber, "CAP_OVERFLOW_ADJUSTED"))
					decision.Overflow = overflow
					decision.Reason = "CAP_OVERFLOW_ADJUSTED"
				} else {
					decision.Reason = strings.ToUpper(string(rule.Kind)) + "_NOT_TRIGGERED"
				}
			}
			decision.Accepted = accepted
			decisions = append(decisions, decision)
		}
		running = candidate
		result.Entries = append(result.Entries, source.copy())
		result.Decisions = append(result.Decisions, decisions...)
		result.Accepted, err = result.Accepted.Add(accepted)
		if err != nil {
			return RuleApplicationResult{}, fmt.Errorf("%w: accepted total: %v", ErrRuleApplicationInvalid, err)
		}
		for _, decision := range decisions {
			result.Rejected, err = result.Rejected.Add(decision.Rejected)
			if err != nil {
				return RuleApplicationResult{}, fmt.Errorf("%w: rejected total: %v", ErrRuleApplicationInvalid, err)
			}
			result.Overflow, err = result.Overflow.Add(decision.Overflow)
			if err != nil {
				return RuleApplicationResult{}, fmt.Errorf("%w: overflow total: %v", ErrRuleApplicationInvalid, err)
			}
		}
	}
	result.Ending, err = running.Quantize(req.Scale, req.Rounding)
	if err != nil {
		return RuleApplicationResult{}, fmt.Errorf("%w: ending: %v", ErrRuleApplicationInvalid, err)
	}
	result.Digest, err = ruleResultDigest(req, result)
	if err != nil {
		return RuleApplicationResult{}, fmt.Errorf("%w: digest: %v", ErrRuleApplicationInvalid, err)
	}
	return result, nil
}

// ApplyBalanceRules is the descriptive spelling of ApplyRules.
func ApplyBalanceRules(req RuleApplicationRequest, ledger []BalanceEntry) (RuleApplicationResult, error) {
	return ApplyRules(req, ledger)
}

func validateRuleApplication(req RuleApplicationRequest) error {
	if strings.TrimSpace(req.AccountID) == "" {
		return fmt.Errorf("%w: account_id is required", ErrRuleApplicationInvalid)
	}
	if err := req.Opening.Validate(); err != nil || req.Opening.Scale() != req.Scale {
		return fmt.Errorf("%w: opening must be valid at scale %d: %v", ErrRuleApplicationInvalid, req.Scale, err)
	}
	if !req.Rounding.Valid() {
		return fmt.Errorf("%w: rounding must be declared", ErrRuleApplicationInvalid)
	}
	seen := make(map[string]struct{}, len(req.Rules))
	for _, rule := range req.Rules {
		if strings.TrimSpace(rule.ID) == "" || strings.TrimSpace(rule.Version) == "" {
			return fmt.Errorf("%w: rule id and version are required", ErrRuleInvalid)
		}
		if rule.Kind != BalanceRuleFloor && rule.Kind != BalanceRuleCap && rule.Kind != BalanceRuleThreshold {
			return fmt.Errorf("%w: unknown kind %q", ErrRuleInvalid, rule.Kind)
		}
		if rule.AppliesTo != "" && rule.AppliesTo != Debit && rule.AppliesTo != Credit {
			return fmt.Errorf("%w: rule %q applies_to must be DEBIT or CREDIT", ErrRuleInvalid, rule.ID)
		}
		if err := rule.Limit.Validate(); err != nil || rule.Limit.Sign() < 0 || rule.Limit.Scale() != req.Scale {
			return fmt.Errorf("%w: rule %q limit must be non-negative and at scale %d: %v", ErrRuleInvalid, rule.ID, req.Scale, err)
		}
		key := rule.ID + "\x00" + rule.Version
		if _, ok := seen[key]; ok {
			return fmt.Errorf("%w: duplicate rule %q/%q", ErrRuleInvalid, rule.ID, rule.Version)
		}
		seen[key] = struct{}{}
	}
	return nil
}

func signedContribution(kind EntryKind, amount values.Decimal) (values.Decimal, error) {
	switch kind {
	case Credit:
		return amount, nil
	case Debit:
		return amount.Neg()
	default:
		return values.Decimal{}, fmt.Errorf("unknown entry kind %q", kind)
	}
}

func makeRuleAdjustment(source BalanceEntry, amount values.Decimal, kind EntryKind, rule BalanceRule, number int, reason string) RuleAdjustment {
	entry := source.copy()
	entry.Kind, entry.Amount, entry.EntryType = kind, amount, RuleApplicationEntryType
	entry.SourceTransactionID = "BAL-004:" + source.IdempotencyKey + ":" + rule.ID
	entry.IdempotencyKey = fmt.Sprintf("BAL-004:%s:%s:%d", source.IdempotencyKey, rule.ID, number)
	return RuleAdjustment{Entry: entry, RuleID: rule.ID, RuleVersion: rule.Version, RuleKind: rule.Kind, Reason: reason, SourceEntry: source.IdempotencyKey}
}

func ruleResultDigest(req RuleApplicationRequest, result RuleApplicationResult) (string, error) {
	w := canonicalbytes.New("hcmnext.domains.balance.RuleApplicationResult", 1).String("account_id", req.AccountID).Value("opening", result.Opening).Value("ending", result.Ending).Value("accepted", result.Accepted).Value("rejected", result.Rejected).Value("overflow", result.Overflow).Count("rules", len(req.Rules))
	for _, rule := range req.Rules {
		w = w.String("rule.id", rule.ID).String("rule.version", rule.Version).String("rule.kind", string(rule.Kind)).String("rule.applies_to", string(rule.AppliesTo)).Value("rule.limit", rule.Limit)
	}
	w = w.Count("entries", len(result.Entries))
	for _, entry := range result.Entries {
		w = w.String("entry", entry.Digest())
	}
	w = w.Count("adjustments", len(result.Adjustments))
	for _, adjustment := range result.Adjustments {
		w = w.String("adjustment.entry", adjustment.Entry.Digest()).String("adjustment.rule_id", adjustment.RuleID).String("adjustment.rule_version", adjustment.RuleVersion).String("adjustment.kind", string(adjustment.RuleKind)).String("adjustment.reason", adjustment.Reason).String("adjustment.source", adjustment.SourceEntry)
	}
	w = w.Count("decisions", len(result.Decisions))
	for _, decision := range result.Decisions {
		w = w.String("decision.source", decision.SourceEntry).String("decision.rule_id", decision.RuleID).String("decision.rule_version", decision.RuleVersion).String("decision.kind", string(decision.RuleKind)).String("decision.reason", decision.Reason).Value("decision.accepted", decision.Accepted).Value("decision.rejected", decision.Rejected).Value("decision.overflow", decision.Overflow).Bool("decision.threshold_breached", decision.ThresholdBreached)
	}
	w = w.Count("events", len(result.Events))
	for _, event := range result.Events {
		w = w.String("event.type", event.Type).String("event.rule_id", event.RuleID).String("event.rule_version", event.RuleVersion).String("event.source", event.SourceEntry).String("event.reason", event.Reason)
	}
	return w.Digest()
}
