package gateevidence

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// reportJSON is the stable JSON projection of a Report: field order fixed
// by declaration order, findings kept in manifest evidence order (never
// re-sorted), so RenderJSON is byte-identical across repeated calls with
// the same Report value.
type reportJSON struct {
	ManifestTodoID string        `json:"manifest_todo_id"`
	ManifestDigest string        `json:"manifest_digest"`
	AsOf           string        `json:"as_of"`
	Decision       GateDecision  `json:"decision"`
	Findings       []findingJSON `json:"findings"`
}

type findingJSON struct {
	TodoID  string  `json:"todo_id"`
	Test    string  `json:"test"`
	Package string  `json:"package"`
	Verdict Verdict `json:"verdict"`
	Detail  string  `json:"detail"`
}

// RenderJSON renders r deterministically: two calls with equal Report
// values always produce byte-identical output.
func RenderJSON(r Report) ([]byte, error) {
	out := reportJSON{
		ManifestTodoID: r.ManifestTodoID,
		ManifestDigest: r.ManifestDigest,
		AsOf:           r.AsOf,
		Decision:       r.Decision,
	}
	for _, f := range r.Findings {
		out.Findings = append(out.Findings, findingJSON(f))
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// RenderMarkdown renders r as a deterministic Markdown report: same input,
// same bytes, every time.
func RenderMarkdown(r Report) []byte {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# P1A Gate Evidence Report\n\n")
	fmt.Fprintf(&buf, "Generated by `tools/planning/gateevidence` (NEXT-003) from the manifest at\n")
	fmt.Fprintf(&buf, "`definitions/planning/gates/p1a-manifest.yaml` (todo `%s`).\n\n", r.ManifestTodoID)
	fmt.Fprintf(&buf, "- **Manifest digest:** `sha256:%s`\n", r.ManifestDigest)
	fmt.Fprintf(&buf, "- **As of:** %s\n", r.AsOf)
	fmt.Fprintf(&buf, "- **Decision:** `%s`\n\n", r.Decision)

	headers := []string{"Todo", "Test", "Package", "Verdict", "Detail"}
	rows := make([][]string, 0, len(r.Findings))
	for _, f := range r.Findings {
		rows = append(rows, []string{
			fmt.Sprintf("`%s`", f.TodoID),
			fmt.Sprintf("`%s`", f.Test),
			fmt.Sprintf("`%s`", f.Package),
			fmt.Sprintf("`%s`", f.Verdict),
			mdEscape(f.Detail),
		})
	}
	buf.Write(renderTable(headers, rows))

	buf.WriteString("\nA `GATE_BLOCKED` decision grants no write authority and is distinct from a\n")
	buf.WriteString("signed Gate A authority decision (`tools/planning/authoritygate`); it only\n")
	buf.WriteString("states whether every named evidence entry currently resolves to `OK`.\n")

	return buf.Bytes()
}

// renderTable renders a GitHub-flavored-Markdown table with every column
// padded to its widest cell, matching the repository's `prettier --write`
// output byte-for-byte - definitions/planning/gates/p1a-evidence-report.md
// is checked in and prettier-formatted (see doc.go), so this package's own
// renderer must produce prettier's exact table shape rather than relying on
// a formatter to leave its output untouched.
func renderTable(headers []string, rows [][]string) []byte {
	widths := make([]int, len(headers))
	for i, h := range headers {
		widths[i] = len(h)
	}
	for _, row := range rows {
		for i, cell := range row {
			if len(cell) > widths[i] {
				widths[i] = len(cell)
			}
		}
	}

	var buf bytes.Buffer
	writeRow := func(cells []string) {
		buf.WriteString("|")
		for i, cell := range cells {
			buf.WriteString(" ")
			buf.WriteString(cell)
			buf.WriteString(strings.Repeat(" ", widths[i]-len(cell)))
			buf.WriteString(" |")
		}
		buf.WriteString("\n")
	}

	writeRow(headers)
	sep := make([]string, len(headers))
	for i, w := range widths {
		sep[i] = strings.Repeat("-", w)
	}
	buf.WriteString("|")
	for _, s := range sep {
		buf.WriteString(" ")
		buf.WriteString(s)
		buf.WriteString(" |")
	}
	buf.WriteString("\n")
	for _, row := range rows {
		writeRow(row)
	}

	return buf.Bytes()
}

// mdEscape neutralizes the one Markdown table hazard a Detail string can
// contain: a literal pipe character.
func mdEscape(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '|' {
			out = append(out, '\\', '|')
			continue
		}
		out = append(out, s[i])
	}
	return string(out)
}
