package sqlckit_test

import (
	"context"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// This package is deliberately test-only. It qualifies the owned SQL and
// repository seams that a future sqlc adapter would have to preserve, without
// importing sqlc or pgx and without putting generated mechanics in production.

const reviewedSchema = `CREATE TABLE account_balance (
    tenant_id text NOT NULL,
    account_id text NOT NULL,
    balance_cents bigint NOT NULL,
    valid_from bigint NOT NULL,
    valid_to bigint NOT NULL,
    PRIMARY KEY (tenant_id, account_id, valid_from)
);`

const reviewedQuery = `SELECT account_id, balance_cents, valid_from, valid_to
FROM account_balance
WHERE tenant_id = $1
  AND account_id = $2
  AND valid_from < $4
  AND valid_to > $3
ORDER BY valid_from DESC
LIMIT 1
FOR UPDATE;`

type column struct {
	name string
	typ  string
}

var reviewedColumns = []column{
	{name: "tenant_id", typ: "text"},
	{name: "account_id", typ: "text"},
	{name: "balance_cents", typ: "bigint"},
	{name: "valid_from", typ: "bigint"},
	{name: "valid_to", typ: "bigint"},
}

type balanceRow struct {
	AccountID    string
	BalanceCents int64
	ValidFrom    int64
	ValidTo      int64
}

// These are the owned ports. Neither interface contains sqlc-generated or
// pgx-specific types; those types, if ever used, must remain below this seam.
type repository interface {
	WithTx(context.Context, func(transaction) error) error
}

type transaction interface {
	GetBalance(context.Context, string, string, int64, int64) (balanceRow, error)
}

func validateSchema(schema []column) error {
	if len(schema) != len(reviewedColumns) {
		return fmt.Errorf("schema has %d columns, want %d", len(schema), len(reviewedColumns))
	}
	for i, want := range reviewedColumns {
		if schema[i] != want {
			return fmt.Errorf("schema column %d = %#v, want %#v", i, schema[i], want)
		}
	}
	return nil
}

func validateReviewedQuery(query string) error {
	lower := strings.ToLower(query)
	for _, required := range []string{
		"tenant_id = $1",
		"account_id = $2",
		"valid_from < $4",
		"valid_to > $3",
		"order by valid_from desc",
		"for update",
	} {
		if !strings.Contains(lower, required) {
			return fmt.Errorf("reviewed query is missing %q", required)
		}
	}
	return nil
}

// renderAuthoredAdapter is a deterministic stand-in for the concrete code
// generated by a candidate. It validates the reviewed schema and SQL first,
// then emits only concrete mechanics. Owner ports and transaction composition
// remain authored above this output boundary.
func renderAuthoredAdapter(schema []column, query string) (string, error) {
	if err := validateSchema(schema); err != nil {
		return "", err
	}
	if err := validateReviewedQuery(query); err != nil {
		return "", err
	}
	return "package adapter\n\nconst getBalanceSQL = `" + query + "`\n", nil
}

func hasConcreteLeak(text string) bool {
	for _, marker := range []string{"pgx.", "pgx/", "sqlc.", "sqlc/", "github.com/sqlc-dev/sqlc"} {
		if strings.Contains(strings.ToLower(text), strings.ToLower(marker)) {
			return true
		}
	}
	return false
}

type fakeDatabase struct {
	row       balanceRow
	err       error
	trace     []string
	lastInput []any
}

func (db *fakeDatabase) WithTx(ctx context.Context, fn func(transaction) error) error {
	if ctx == nil {
		return errors.New("nil context")
	}
	db.trace = append(db.trace, "BEGIN")
	err := fn((*fakeTransaction)(db))
	if err != nil {
		db.trace = append(db.trace, "ROLLBACK")
		return err
	}
	db.trace = append(db.trace, "COMMIT")
	return nil
}

type fakeTransaction fakeDatabase

func (tx *fakeTransaction) GetBalance(_ context.Context, tenant, account string, from, to int64) (balanceRow, error) {
	db := (*fakeDatabase)(tx)
	db.trace = append(db.trace, "QUERY")
	db.lastInput = []any{tenant, account, from, to}
	return db.row, db.err
}

func readBalance(ctx context.Context, repo repository, tenant, account string, from, to int64) (balanceRow, error) {
	var result balanceRow
	err := repo.WithTx(ctx, func(tx transaction) error {
		var err error
		result, err = tx.GetBalance(ctx, tenant, account, from, to)
		return err
	})
	return result, err
}

// TestSQLCQualificationPreservesOwnedRepositoryAndTransactionBoundaries is
// LIB-017's primary test. It proves the current authored-SQL alternative has
// the exact temporal and locking semantics, typed result mapping, and explicit
// transaction boundary that a future sqlc adapter must preserve.
func TestSQLCQualificationPreservesOwnedRepositoryAndTransactionBoundaries(t *testing.T) {
	if err := validateReviewedQuery(reviewedQuery); err != nil {
		t.Fatalf("reviewed query: %v", err)
	}
	first, err := renderAuthoredAdapter(reviewedColumns, reviewedQuery)
	if err != nil {
		t.Fatalf("first offline render: %v", err)
	}
	second, err := renderAuthoredAdapter(reviewedColumns, reviewedQuery)
	if err != nil {
		t.Fatalf("second offline render: %v", err)
	}
	if first != second {
		t.Fatal("authored adapter render is not byte-stable")
	}
	if hasConcreteLeak(first) {
		t.Fatal("concrete adapter output leaks sqlc/pgx type markers")
	}

	db := &fakeDatabase{row: balanceRow{AccountID: "acct-1", BalanceCents: 1250, ValidFrom: 10, ValidTo: 20}}
	got, err := readBalance(context.Background(), db, "tenant-1", "acct-1", 12, 18)
	if err != nil {
		t.Fatalf("readBalance: %v", err)
	}
	if got != db.row {
		t.Fatalf("typed row = %#v, want %#v", got, db.row)
	}
	if !reflect.DeepEqual(db.trace, []string{"BEGIN", "QUERY", "COMMIT"}) {
		t.Fatalf("transaction trace = %v, want BEGIN QUERY COMMIT", db.trace)
	}
	if !reflect.DeepEqual(db.lastInput, []any{"tenant-1", "acct-1", int64(12), int64(18)}) {
		t.Fatalf("query input = %#v", db.lastInput)
	}
}

type qualificationManifest struct {
	Version                         int    `yaml:"version"`
	Todo                            string `yaml:"todo"`
	Tool                            string `yaml:"tool"`
	Role                            string `yaml:"role"`
	Verdict                         string `yaml:"verdict"`
	RuntimeDependencyGraphUnchanged bool   `yaml:"runtime_dependency_graph_unchanged"`
	Command                         string `yaml:"command"`
	Decision                        string `yaml:"decision"`
	RemovalPath                     string `yaml:"removal_path"`
	Candidate                       struct {
		Source                string `yaml:"source"`
		License               string `yaml:"license"`
		LatestReviewedRelease string `yaml:"latest_reviewed_release"`
		MaintenanceEvidence   string `yaml:"maintenance_evidence"`
		ReplacementPath       string `yaml:"replacement_path"`
	} `yaml:"candidate"`
	Alternative struct {
		Name           string   `yaml:"name"`
		Implementation string   `yaml:"implementation"`
		Packages       []string `yaml:"packages"`
		Contract       string   `yaml:"contract"`
	} `yaml:"alternative"`
	Scope struct {
		Covers   []string `yaml:"covers"`
		Excludes []string `yaml:"excludes"`
	} `yaml:"scope"`
	Evidence []struct {
		Test    string `yaml:"test"`
		Package string `yaml:"package"`
	} `yaml:"evidence"`
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	for {
		if info, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil && !info.IsDir() {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatalf("no go.mod found walking from %s", file)
		}
		dir = parent
	}
}

func loadManifest(t *testing.T) qualificationManifest {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(repoRoot(t), "definitions", "architecture", "sqlc-qualification.yaml"))
	if err != nil {
		t.Fatalf("read qualification manifest: %v", err)
	}
	var m qualificationManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		t.Fatalf("parse qualification manifest: %v", err)
	}
	return m
}

// TestTodo_LIB_017_Golden pins the authored SQL contract and the explicit
// rejection decision. The exact query text protects temporal and lock clauses
// from being silently dropped by a future generator experiment.
func TestTodo_LIB_017_Golden(t *testing.T) {
	m := loadManifest(t)
	if m.Version != 1 || m.Todo != "LIB-017" || m.Tool != "github.com/sqlc-dev/sqlc/cmd/sqlc" {
		t.Fatalf("manifest identity = version %d todo %q tool %q", m.Version, m.Todo, m.Tool)
	}
	if m.Role != "substrate" || m.Verdict != "REJECT" || !m.RuntimeDependencyGraphUnchanged {
		t.Fatalf("decision = role %q verdict %q unchanged=%v", m.Role, m.Verdict, m.RuntimeDependencyGraphUnchanged)
	}
	if m.Candidate.Source == "" || m.Candidate.License == "" || m.Candidate.LatestReviewedRelease == "" || m.Candidate.MaintenanceEvidence == "" || m.Candidate.ReplacementPath == "" {
		t.Fatal("candidate evidence is incomplete")
	}
	if m.Decision == "" || m.RemovalPath == "" {
		t.Fatal("decision and removal_path are required")
	}
	wantSchema := []column{
		{name: "tenant_id", typ: "text"}, {name: "account_id", typ: "text"},
		{name: "balance_cents", typ: "bigint"}, {name: "valid_from", typ: "bigint"},
		{name: "valid_to", typ: "bigint"},
	}
	if !reflect.DeepEqual(reviewedColumns, wantSchema) {
		t.Fatalf("schema golden drift: %#v", reviewedColumns)
	}
	if reviewedQuery != `SELECT account_id, balance_cents, valid_from, valid_to
FROM account_balance
WHERE tenant_id = $1
  AND account_id = $2
  AND valid_from < $4
  AND valid_to > $3
ORDER BY valid_from DESC
LIMIT 1
FOR UPDATE;` {
		t.Fatal("reviewed SQL golden drift")
	}
}

// TestTodo_LIB_017_Integration exercises the authored adapter against a
// deterministic in-memory PostgreSQL-shaped transaction fixture, including
// rollback on query failure.
func TestTodo_LIB_017_Integration(t *testing.T) {
	t.Run("commit_preserves_typed_result", func(t *testing.T) {
		db := &fakeDatabase{row: balanceRow{AccountID: "a", BalanceCents: 99, ValidFrom: 1, ValidTo: 9}}
		got, err := readBalance(context.Background(), db, "t", "a", 2, 8)
		if err != nil || got.BalanceCents != 99 {
			t.Fatalf("result=%#v err=%v", got, err)
		}
		if !reflect.DeepEqual(db.trace, []string{"BEGIN", "QUERY", "COMMIT"}) {
			t.Fatalf("trace=%v", db.trace)
		}
	})
	t.Run("query_error_rolls_back", func(t *testing.T) {
		db := &fakeDatabase{err: errors.New("schema failure")}
		if _, err := readBalance(context.Background(), db, "t", "a", 2, 8); err == nil {
			t.Fatal("expected query error")
		}
		if !reflect.DeepEqual(db.trace, []string{"BEGIN", "QUERY", "ROLLBACK"}) {
			t.Fatalf("trace=%v", db.trace)
		}
	})
}

// TestTodo_LIB_017_Mutation proves strict schema/query checks reject the
// mutations that make generated adapter code unsafe: dropped/type-changed
// columns, temporal predicate loss, and lock loss.
func TestTodo_LIB_017_Mutation(t *testing.T) {
	for i := range reviewedColumns {
		mutated := append([]column(nil), reviewedColumns[:i]...)
		mutated = append(mutated, reviewedColumns[i+1:]...)
		mutated = append(mutated, reviewedColumns[i])
		mutated = mutated[:len(mutated)-1]
		if err := validateSchema(mutated); err == nil {
			t.Errorf("dropped column %d accepted", i)
		}
	}
	for i := range reviewedColumns {
		mutated := append([]column(nil), reviewedColumns...)
		mutated[i].typ = "text"
		if mutated[i].typ == reviewedColumns[i].typ {
			mutated[i].typ = "integer"
		}
		if err := validateSchema(mutated); err == nil {
			t.Errorf("type mutation %d accepted", i)
		}
	}
	for _, marker := range []string{"valid_from < $4", "valid_to > $3", "FOR UPDATE"} {
		mutated := strings.Replace(reviewedQuery, marker, "", 1)
		if err := validateReviewedQuery(mutated); err == nil {
			t.Errorf("query mutation removing %q accepted", marker)
		}
	}
	output, err := renderAuthoredAdapter(reviewedColumns, reviewedQuery)
	if err != nil {
		t.Fatalf("baseline render: %v", err)
	}
	if hasConcreteLeak(output+" pgx.Tx sqlc.Queries") == false {
		t.Fatal("concrete-type leak detector failed its mutation")
	}
}

// TestTodo_LIB_017_Conformance checks evidence and ensures neither sqlc nor
// generated pgx/sqlc types entered this repository's module declarations or
// this qualification package's actual imports.
func TestTodo_LIB_017_Conformance(t *testing.T) {
	root := repoRoot(t)
	m := loadManifest(t)
	want := map[string]bool{
		"TestSQLCQualificationPreservesOwnedRepositoryAndTransactionBoundaries": false,
		"TestTodo_LIB_017_Golden":      false,
		"TestTodo_LIB_017_Integration": false,
		"TestTodo_LIB_017_Mutation":    false,
		"TestTodo_LIB_017_Conformance": false,
	}
	for _, ev := range m.Evidence {
		if _, ok := want[ev.Test]; !ok {
			t.Errorf("unexpected evidence test %q", ev.Test)
			continue
		}
		if want[ev.Test] {
			t.Errorf("duplicate evidence test %q", ev.Test)
		}
		want[ev.Test] = true
		if ev.Package != "tools/quality/sqlckit" {
			t.Errorf("%s evidence package = %q", ev.Test, ev.Package)
		}
	}
	for name, found := range want {
		if !found {
			t.Errorf("evidence missing %q", name)
		}
	}
	if m.Command != "go test -count=1 ./tools/quality/sqlckit" {
		t.Errorf("command = %q", m.Command)
	}
	for _, name := range []string{"go.mod", "go.sum"} {
		data, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		lower := strings.ToLower(string(data))
		if strings.Contains(lower, "github.com/sqlc-dev/sqlc") || strings.Contains(lower, "sqlc.dev") {
			t.Fatalf("%s admits sqlc despite REJECT decision", name)
		}
	}
	var leaks []string
	// Existing PostgreSQL adapters are intentionally allowed to import pgx;
	// this qualification lane proves that the owned test/port fixture itself
	// does not acquire those concrete types. A future generated adapter must be
	// checked at its own concrete-adapter root before admission.
	fixtureRoot := filepath.Join(root, "tools", "quality", "sqlckit")
	err := filepath.WalkDir(fixtureRoot, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		parsed, parseErr := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly)
		if parseErr != nil {
			return parseErr
		}
		for _, imported := range parsed.Imports {
			name := strings.Trim(imported.Path.Value, `"`)
			if strings.Contains(name, "sqlc") || strings.Contains(name, "pgx") {
				leaks = append(leaks, path+":"+name)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("scan imports: %v", err)
	}
	if len(leaks) != 0 {
		sort.Strings(leaks)
		t.Fatalf("sqlc/pgx imports found: %v", leaks)
	}
	if len(strings.TrimSpace(reviewedSchema)) == 0 || len(strings.TrimSpace(reviewedQuery)) == 0 {
		t.Fatal("reviewed SQL fixture is empty")
	}
}
