//go:build !js || !wasm

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

func TestTodo_WEB_031_Conformance(t *testing.T) {
	root, err := repositoryRoot()
	if err != nil {
		t.Fatal(err)
	}
	approvedAdapter := filepath.Join("tools", "uxqual", "cmd", "journeywasm", "browser_history_wasm.go")
	violations, err := browserStorageSourceViolations(root, approvedAdapter)
	if err != nil {
		t.Fatal(err)
	}
	if len(violations) != 0 {
		t.Fatalf("browser-storage source boundary violations:\n%s", strings.Join(violations, "\n"))
	}
}

func TestTodo_WEB_031_SourceGate(t *testing.T) {
	const approvedRelative = "tools/uxqual/cmd/journeywasm/browser_history_wasm.go"
	const approvedSource = `package main
func approved(global, storage sourceGateJSValue) {
	browserProperty(global, "session" + "Storage")
	browserCall(storage, "getItem", "key")
	browserCall(storage, "setItem", "key", "value")
}
`
	newFixture := func(t *testing.T) string {
		t.Helper()
		root := t.TempDir()
		writeSourceGateFixture(t, root, approvedRelative, approvedSource)
		return root
	}
	assertViolation := func(t *testing.T, root, want string) {
		t.Helper()
		violations, err := browserStorageSourceViolations(root, approvedRelative)
		if err != nil {
			t.Fatal(err)
		}
		if joined := strings.Join(violations, "\n"); !strings.Contains(joined, want) {
			t.Fatalf("violations = %q, want text %q", joined, want)
		}
	}

	t.Run("baseline and non-source artifacts", func(t *testing.T) {
		root := newFixture(t)
		for _, path := range []string{
			".codex-build/browser.go", "_build/browser.go", "node_modules/browser.go",
			"testdata/browser.go", "vendor/browser.go",
		} {
			writeSourceGateFixture(t, root, path, `package ignored; func f(v sourceGateJSValue) { v.Get("localStorage") }`)
		}
		violations, err := browserStorageSourceViolations(root, approvedRelative)
		if err != nil {
			t.Fatal(err)
		}
		if len(violations) != 0 {
			t.Fatalf("artifact directories affected source gate: %v", violations)
		}
	})

	t.Run("build and generated production source remain covered", func(t *testing.T) {
		root := newFixture(t)
		for _, path := range []string{"build/browser.go", "dist/browser.go", "gen/browser.go", "internal/generated/browser.go", "out/browser.go"} {
			writeSourceGateFixture(t, root, path, "// Code generated by fixture. DO NOT EDIT.\npackage generated\nfunc f(v sourceGateJSValue) { v.Get(\"indexedDB\") }\n")
		}
		assertViolation(t, root, `build/browser.go acquires forbidden browser storage API "indexedDB"`)
		assertViolation(t, root, `gen/browser.go acquires forbidden browser storage API "indexedDB"`)
	})

	t.Run("moved storage call", func(t *testing.T) {
		root := newFixture(t)
		writeSourceGateFixture(t, root, "internal/moved.go", `package internal; func moved(v sourceGateJSValue) { v.Call("setItem", "key", "value") }`)
		assertViolation(t, root, "internal/moved.go contains setItem call outside the approved adapter")
	})

	t.Run("forbidden API in approved adapter", func(t *testing.T) {
		root := newFixture(t)
		writeSourceGateFixture(t, root, approvedRelative, approvedSource+`func forbidden(v sourceGateJSValue) { v.Get("local" + "Storage") }`)
		assertViolation(t, root, `acquires forbidden browser storage API "localStorage"`)
	})
}

func writeSourceGateFixture(t *testing.T, root, relative, body string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(relative))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

// browserStorageSourceViolations parses production Go source rather than
// searching comments or Go-ignored artifact directories. Generated and
// build-named Go remain in scope because they can be compiled release source.
// The gate pins acquisition and browser Web Storage calls to one reviewed
// adapter, including the calls themselves: moving getItem/setItem while leaving
// the global acquisition behind cannot evade the gate, and forbidden APIs
// remain forbidden inside the approved file.
func browserStorageSourceViolations(root, approvedAdapter string) ([]string, error) {
	approvedAdapter, err := filepath.Abs(filepath.Join(root, approvedAdapter))
	if err != nil {
		return nil, err
	}
	approvedAdapter = filepath.Clean(approvedAdapter)
	approvedCounts := map[string]int{}
	var violations []string
	walkErr := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if path != root && ignoredBrowserStorageSourceDir(entry.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if filepath.Ext(path) != ".go" || strings.HasSuffix(entry.Name(), "_test.go") {
			return nil
		}
		body, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		parsed, parseErr := parser.ParseFile(token.NewFileSet(), path, body, parser.SkipObjectResolution)
		if parseErr != nil {
			return parseErr
		}
		constants := sourceStringConstants(parsed)
		ast.Inspect(parsed, func(node ast.Node) bool {
			call, callOK := node.(*ast.CallExpr)
			if !callOK || len(call.Args) == 0 {
				return true
			}
			operation := ""
			nameExpression := call.Args[0]
			switch function := call.Fun.(type) {
			case *ast.SelectorExpr:
				if function.Sel.Name != "Get" && function.Sel.Name != "Call" {
					return true
				}
				operation = function.Sel.Name
			case *ast.Ident:
				if (function.Name != "browserProperty" && function.Name != "browserCall") || len(call.Args) < 2 {
					return true
				}
				if function.Name == "browserProperty" {
					operation = "Get"
				} else {
					operation = "Call"
				}
				nameExpression = call.Args[1]
			default:
				return true
			}
			name, literalOK := sourceConstantString(nameExpression, constants, nil)
			if !literalOK {
				return true
			}
			kind := ""
			switch operation {
			case "Get":
				switch name {
				case "sessionStorage":
					kind = "sessionStorage acquisition"
				case "localStorage", "indexedDB", "caches", "cacheStorage", "CacheStorage":
					violations = append(violations, fmt.Sprintf("%s acquires forbidden browser storage API %q", sourceRelativePath(root, path), name))
				}
			case "Call":
				switch name {
				case "getItem", "setItem":
					kind = name + " call"
				case "removeItem", "clear", "key":
					violations = append(violations, fmt.Sprintf("%s invokes forbidden browser-storage method %q", sourceRelativePath(root, path), name))
				}
			}
			if kind != "" {
				if filepath.Clean(path) != approvedAdapter {
					violations = append(violations, fmt.Sprintf("%s contains %s outside the approved adapter", sourceRelativePath(root, path), kind))
				} else {
					approvedCounts[kind]++
				}
			}
			return true
		})
		return nil
	})
	if walkErr != nil {
		return nil, walkErr
	}
	for _, kind := range []string{"sessionStorage acquisition", "getItem call", "setItem call"} {
		if approvedCounts[kind] != 1 {
			violations = append(violations, fmt.Sprintf("approved adapter has %d %s uses, want exactly one", approvedCounts[kind], kind))
		}
	}
	sort.Strings(violations)
	return violations, nil
}

func ignoredBrowserStorageSourceDir(name string) bool {
	if strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
		return true
	}
	switch strings.ToLower(name) {
	case "node_modules", "testdata", "vendor":
		return true
	default:
		return false
	}
}

func sourceStringConstants(file *ast.File) map[string]ast.Expr {
	constants := make(map[string]ast.Expr)
	ast.Inspect(file, func(node ast.Node) bool {
		declaration, ok := node.(*ast.GenDecl)
		if !ok || declaration.Tok != token.CONST {
			return true
		}
		for _, spec := range declaration.Specs {
			valueSpec, valueOK := spec.(*ast.ValueSpec)
			if !valueOK {
				continue
			}
			for index, name := range valueSpec.Names {
				if index < len(valueSpec.Values) {
					constants[name.Name] = valueSpec.Values[index]
				}
			}
		}
		return true
	})
	return constants
}

func sourceConstantString(expression ast.Expr, constants map[string]ast.Expr, visiting map[string]bool) (string, bool) {
	switch value := expression.(type) {
	case *ast.BasicLit:
		if value.Kind != token.STRING {
			return "", false
		}
		decoded, err := strconv.Unquote(value.Value)
		return decoded, err == nil
	case *ast.BinaryExpr:
		if value.Op != token.ADD {
			return "", false
		}
		left, leftOK := sourceConstantString(value.X, constants, visiting)
		right, rightOK := sourceConstantString(value.Y, constants, visiting)
		return left + right, leftOK && rightOK
	case *ast.ParenExpr:
		return sourceConstantString(value.X, constants, visiting)
	case *ast.Ident:
		if visiting == nil {
			visiting = make(map[string]bool)
		}
		if visiting[value.Name] {
			return "", false
		}
		constant, ok := constants[value.Name]
		if !ok {
			return "", false
		}
		visiting[value.Name] = true
		result, resultOK := sourceConstantString(constant, constants, visiting)
		delete(visiting, value.Name)
		return result, resultOK
	default:
		return "", false
	}
}

func sourceRelativePath(root, path string) string {
	relative, err := filepath.Rel(root, path)
	if err != nil {
		return filepath.ToSlash(path)
	}
	return filepath.ToSlash(relative)
}

func repositoryRoot() (string, error) {
	path, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
			return path, nil
		}
		parent := filepath.Dir(path)
		if parent == path {
			return "", os.ErrNotExist
		}
		path = parent
	}
}
