package productslice

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

// RegistrySchema and RegistrySchemaVersion identify the file-level shape
// definitions/planning/product-slices.yaml is generated in. SchemaVersion
// changes only when that shape itself changes, never when the admitted
// slices change.
const (
	RegistrySchema        = "hcmnext.planning.productslice.registry"
	RegistrySchemaVersion = 1
)

// Registry is the file-level container definitions/planning/
// product-slices.yaml holds: every admitted [ProductSliceDefinition] plus a
// stable digest over them (excluding Digest itself), so a byte-for-byte
// drift check can prove a checked-in file still matches a fresh generation
// (mirroring intentmanifests.FeatureIntentCoverageRegistry's own digest
// convention).
type Registry struct {
	Schema        string                   `yaml:"schema" json:"schema"`
	SchemaVersion int                      `yaml:"schema_version" json:"schema_version"`
	Slices        []ProductSliceDefinition `yaml:"slices" json:"slices"`
	Digest        string                   `yaml:"digest" json:"digest"`
}

// NewRegistry builds a Registry from slices, computing its digest.
func NewRegistry(slices ...ProductSliceDefinition) Registry {
	r := Registry{
		Schema:        RegistrySchema,
		SchemaVersion: RegistrySchemaVersion,
		Slices:        append([]ProductSliceDefinition(nil), slices...),
	}
	r.Digest = r.computeDigest()
	return r
}

// computeDigest returns the registry's stable content digest: canonical
// JSON over the schema tag and every slice (each slice's own reference
// lists sorted via ProductSliceDefinition.sorted, slices themselves ordered
// by SliceID), with Digest itself always cleared first so the digest never
// depends on its own prior value.
func (r Registry) computeDigest() string {
	sorted := make([]ProductSliceDefinition, len(r.Slices))
	for i, s := range r.Slices {
		sorted[i] = s.sorted()
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].SliceID < sorted[j].SliceID })
	b, _ := json.Marshal(struct {
		Schema        string                   `json:"schema"`
		SchemaVersion int                      `json:"schema_version"`
		Slices        []ProductSliceDefinition `json:"slices"`
	}{r.Schema, r.SchemaVersion, sorted})
	sum := sha256.Sum256(b)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// VerifyDigest reports whether r.Digest matches r.computeDigest(): the file
// was not hand-edited after generation without regenerating its digest.
func (r Registry) VerifyDigest() error {
	want := r.computeDigest()
	if r.Digest != want {
		return fmt.Errorf("productslice: registry digest=%q, want %q (regenerate with `go run ./tools/planning/cmd/productslice`)", r.Digest, want)
	}
	return nil
}

// Validate resolves every slice in r against reg and additionally rejects a
// duplicate SliceID across slices (two admitted slices must never share an
// identity).
func (r Registry) Validate(reg Registries) []Violation {
	var violations []Violation
	seen := make(map[string]bool, len(r.Slices))
	for _, s := range r.Slices {
		if seen[s.SliceID] {
			violations = append(violations, Violation{Field: "slice_id", Ref: s.SliceID, Detail: "duplicate slice id in registry"})
		}
		seen[s.SliceID] = true
		for _, v := range s.Validate(reg) {
			v.Detail = fmt.Sprintf("slice %s: %s", s.SliceID, v.Detail)
			violations = append(violations, v)
		}
	}
	return violations
}

// LoadRegistryYAML reads and parses a product-slice registry file. It does
// not itself call Validate or VerifyDigest -- callers choose which checks
// they need (a Golden test may skip live Validate; a Conformance test wants
// both).
func LoadRegistryYAML(path string) (Registry, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Registry{}, fmt.Errorf("productslice: reading %s: %w", path, err)
	}
	var r Registry
	if err := yaml.Unmarshal(data, &r); err != nil {
		return Registry{}, fmt.Errorf("productslice: parsing %s: %w", path, err)
	}
	return r, nil
}

// MarshalRegistryYAML recomputes r's digest and renders it as YAML. The
// generator command and this package's drift test both call this so the
// serialization is defined exactly once.
func MarshalRegistryYAML(r Registry) ([]byte, error) {
	r.Digest = r.computeDigest()
	data, err := yaml.Marshal(r)
	if err != nil {
		return nil, fmt.Errorf("productslice: marshaling registry to YAML: %w", err)
	}
	return data, nil
}

// GeneratedFileHeader is prepended to definitions/planning/
// product-slices.yaml by the generator command. It is exported so the
// drift test builds the exact same bytes the command would write, instead
// of re-typing the header text a second time where it could drift.
const GeneratedFileHeader = "" +
	"# Code generated by `go run ./tools/planning/cmd/productslice`. DO NOT EDIT.\n" +
	"# ALIGN-001: this file is regenerated from the real registries it references\n" +
	"# (feature/intent coverage, capability BOOTSTRAP, the live Phase 1 package\n" +
	"# closure, and the todo registry). A drift test proves it still matches a\n" +
	"# fresh run of the generator.\n"

// RenderRegistryFile returns the exact bytes the generator command writes:
// [GeneratedFileHeader] followed by r's canonical YAML.
func RenderRegistryFile(r Registry) ([]byte, error) {
	data, err := MarshalRegistryYAML(r)
	if err != nil {
		return nil, err
	}
	out := make([]byte, 0, len(GeneratedFileHeader)+len(data))
	out = append(out, GeneratedFileHeader...)
	out = append(out, data...)
	return out, nil
}
